# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Detail',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Hotel_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departure_city', models.CharField(max_length=20)),
                ('arrival_city', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('ticket_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_city', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('arrival_time', models.DateTimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Train')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hotel_room',
            unique_together=set([('room_no', 'hotel')]),
        ),
    ]
