# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170326_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cid', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('abb_state', models.CharField(max_length=10)),
            ],
        ),
    ]
