# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Hotel_Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Train_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Train_Sub_Order',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_train_schedule', to='webapp.Train_Schedule')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_train_schedule', to='webapp.Train_Schedule')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Train')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
